version: '3'

services:
  {% if cookiecutter.rabbitmq.lower().startswith('y') %}
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15671:15671"
      - "15672:15672"
      - "25672:25672"
      - "4349:4349"
      - "5671:5671"
      - "5672:5672"
  {% endif %}{% if cookiecutter.redis.lower().startswith('y') %}
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  {% endif %}{% if cookiecutter.minio.lower().startswith('y') %}
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
  {% endif %}{% if cookiecutter.elasticsearch.lower().startswith('y') %}
  elasticsearch:
    image: elasticsearch:6.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
  {% endif %}{% if cookiecutter.kibana.lower().startswith('y') %}
  kibana:
    image: kibana:6.6.2
    ports:
      - "5601:5601"
  {% endif %}{% if cookiecutter.postgres.lower().startswith('y') %}
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
  {% endif %}{% if cookiecutter.consul.lower().startswith('y') %}
  consul:
    image: consul:1.4.4
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8500:8500"
      - "8600:8600"
  {% endif %}
